/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iventm;
import DBconnect.DBconnect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;



/**
 *
 * @author Shani
 */
public class INSERTEvent extends javax.swing.JFrame {

    Connection conn = null;  
    PreparedStatement pst =null;
    ResultSet rs = null;
    /**
     * Creates new form INSERTEvent
     */
    public INSERTEvent() {
        initComponents();
        {
            Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
            setSize(d);
        }
        conn = DBconnect.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aaaaaaaaaaaaaaasvfvdseventm.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1360, 180);

        jLabel3.setText("ivent items");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(460, 60, 130, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1360, 160);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 153));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setFocusCycleRoot(true);
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 204, 153));
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel4.setText("SILVER PAC");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(50, 0, 220, 40);
        jPanel5.add(jTextField1);
        jTextField1.setBounds(140, 400, 140, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("select full pac ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(70, 450, 130, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("TOTAL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(10, 400, 100, 30);

        jLabel13.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel13.setText("Full pac:- 45000 Rs.");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(60, 30, 180, 40);

        jCheckBox1.setText("jCheckBox1");
        jPanel5.add(jCheckBox1);
        jCheckBox1.setBounds(50, 100, 170, 30);

        jCheckBox2.setText("jCheckBox2");
        jPanel5.add(jCheckBox2);
        jCheckBox2.setBounds(50, 150, 170, 30);

        jCheckBox3.setText("jCheckBox3");
        jPanel5.add(jCheckBox3);
        jCheckBox3.setBounds(50, 200, 170, 30);

        jCheckBox4.setText("jCheckBox4");
        jPanel5.add(jCheckBox4);
        jCheckBox4.setBounds(50, 250, 170, 30);

        jCheckBox5.setText("jCheckBox5");
        jPanel5.add(jCheckBox5);
        jCheckBox5.setBounds(50, 300, 170, 30);

        jCheckBox6.setText("jCheckBox6");
        jPanel5.add(jCheckBox6);
        jCheckBox6.setBounds(50, 350, 170, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(240, 10, 300, 520);

        jPanel6.setBackground(new java.awt.Color(255, 204, 153));
        jPanel6.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel5.setText("GOLD PAC");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(80, 0, 180, 30);
        jPanel6.add(jTextField2);
        jTextField2.setBounds(150, 400, 150, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Select pac");
        jButton2.setToolTipText("");
        jPanel6.add(jButton2);
        jButton2.setBounds(90, 440, 140, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("TOTAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(20, 400, 100, 31);

        jLabel14.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel14.setText("Full pac:- 78000 Rs.");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(80, 30, 200, 30);

        jCheckBox7.setText("jCheckBox7");
        jPanel6.add(jCheckBox7);
        jCheckBox7.setBounds(80, 100, 170, 30);

        jCheckBox8.setText("jCheckBox8");
        jPanel6.add(jCheckBox8);
        jCheckBox8.setBounds(80, 150, 170, 30);

        jCheckBox9.setText("jCheckBox9");
        jPanel6.add(jCheckBox9);
        jCheckBox9.setBounds(80, 200, 170, 30);

        jCheckBox10.setText("jCheckBox10");
        jPanel6.add(jCheckBox10);
        jCheckBox10.setBounds(80, 250, 170, 30);

        jCheckBox11.setText("jCheckBox11");
        jPanel6.add(jCheckBox11);
        jCheckBox11.setBounds(80, 300, 170, 30);

        jCheckBox12.setText("jCheckBox12");
        jPanel6.add(jCheckBox12);
        jCheckBox12.setBounds(80, 350, 170, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(570, 10, 320, 530);

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));
        jPanel7.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel6.setText("PLATINUM PAC");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(40, -10, 260, 60);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField3);
        jTextField3.setBounds(140, 400, 160, 30);

        jButton3.setBackground(new java.awt.Color(204, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Select pac");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(100, 440, 130, 40);

        jButton6.setBackground(new java.awt.Color(153, 51, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("TOTAL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(30, 400, 90, 30);

        jLabel15.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel15.setText("Full pac:- 84000 Rs.");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(70, 30, 170, 30);

        jCheckBox13.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox13.setText("21000 Rs.");
        jPanel7.add(jCheckBox13);
        jCheckBox13.setBounds(70, 100, 180, 30);

        jCheckBox14.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox14.setText("20000 Rs.");
        jPanel7.add(jCheckBox14);
        jCheckBox14.setBounds(70, 150, 180, 30);

        jCheckBox15.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox15.setText("15000 Rs.");
        jPanel7.add(jCheckBox15);
        jCheckBox15.setBounds(70, 200, 180, 30);

        jCheckBox16.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox16.setText("10500 Rs.");
        jPanel7.add(jCheckBox16);
        jCheckBox16.setBounds(70, 250, 180, 30);

        jCheckBox17.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox17.setText("9000 Rs.");
        jPanel7.add(jCheckBox17);
        jCheckBox17.setBounds(70, 300, 180, 30);

        jCheckBox18.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox18.setText("10000 Rs.");
        jPanel7.add(jCheckBox18);
        jCheckBox18.setBounds(70, 350, 180, 30);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(920, 10, 310, 540);

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel7.setText("Poruwa");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(40, 120, 140, 30);

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel8.setText("Setiback");
        jLabel8.setToolTipText("");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(40, 170, 150, 30);

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel9.setText("Front Decos");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 210, 150, 30);

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel10.setText("Shamphane table or ");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 250, 190, 40);

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel11.setText("Oil lamp");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(40, 310, 90, 40);

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel12.setText("Cake");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 350, 80, 40);
        jPanel4.add(jTabbedPane2);
        jTabbedPane2.setBounds(50, -30, 30, 20);

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel1.setText("milk pot table");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(40, 270, 150, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 10, 1360, 590);

        jTabbedPane1.addTab("pacage", jPanel3);

        jTabbedPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.addTab("themes& other items ", jTabbedPane3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 160, 1370, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // for platinum pacage all select
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // for the platinum pacage selected items
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INSERTEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INSERTEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INSERTEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INSERTEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INSERTEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
