/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iventm;


import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import DBconnect.DBconnect;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Shani
 */
public class MainInterface extends javax.swing.JFrame {
    
    Connection conn = null;  
    PreparedStatement pst =null;
    ResultSet rs = null;
    
    
        String eventId ;
        String custID ;
        String name;
        String address;
        String tp1 ;
        String tp2;
       
    
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        {
            Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
            setSize(d);
        }
        conn = DBconnect.connect();
        
        //table lioad
      //  lblid.setText(eventId);
       // lblCustID.setText(custID);
      
       
       // set auto date and time on top of the page 
       
       date.setFont(new Font("Times new Roman",1,18));
       time.setFont(new Font("Times new Roman",1,18));
          ShowTime();
        
        
    }
    
    
    public void ShowTime(){

      Thread t=new Thread(){
      public void run(){
           for(;;){
              Calendar calenda=new GregorianCalendar();
              int day=calenda.get(calenda.DAY_OF_MONTH);
              int month=calenda.get(calenda.MONTH);
              int year=calenda.get(calenda.YEAR);
              date.setText("Date :"+day+"/"+(month+1)+"/"+year);
              
              
              
              int hour=calenda.get(calenda.HOUR);
              int minute=calenda.get(calenda.MINUTE);
              int Second=calenda.get(calenda.SECOND);
              
              time.setText("Time :" +hour+ ":" +minute+ ":" +Second);
              try{
                 sleep(1000);
                 
              }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
              }
           }
      };
             
      t.start();
      
}
    public void setvalues(){
    
    try{
         lblid.setText(eventId);
         lblCustID.setText(custID);
    
    }
    catch(Exception e){
    
    
    }   
    
    
    }
        public void customer_details(){
            
            
            
            
    tableload1();
   
    
    
    
    
    }
    
    public void tableload1(){
    
        try{
            String sql="SELECT CustID,customerName,tel1 FROM customer WHERE eventId ='"+lblid+"' ";
              pst = conn.prepareStatement(sql);
            rs= pst.executeQuery(sql);
            tblCustomer.setModel(DbUtils.resultSetToTableModel(rs));
            
            String sql1="SELECT no_of_gusts,EventType FROM event WHERE  eventId ='"+lblid+"' ";
           pst = conn.prepareStatement(sql1);
            rs= pst.executeQuery(sql1);
            tblCustomer.setModel(DbUtils.resultSetToTableModel(rs));
            
        
        }
        catch(Exception e){
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbxtime = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbxhall = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        txbxdate = new javax.swing.JTextField();
        txbxavalability = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txbxaddress = new javax.swing.JTextField();
        txbxname = new javax.swing.JTextField();
        txbxtp1 = new javax.swing.JTextField();
        txbxtp2 = new javax.swing.JTextField();
        butnSave = new javax.swing.JButton();
        butnDelete = new javax.swing.JButton();
        butnCancel = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cmbxeType = new javax.swing.JComboBox<>();
        txbxgustno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblCustID = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        txbxsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setText("event date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 60, 100, 30);

        cmbxtime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning to Aftrnoon (8.00 pm to 4.00 pm )", "Afternoon to Evening(12.00 pm to 7.00 pm)", "Evening to Night (6.00 pm to 12.00 am)", "Full day(8.00 am to 10.00 pm)" }));
        jPanel1.add(cmbxtime);
        cmbxtime.setBounds(270, 110, 250, 30);

        jLabel3.setText("event time");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 120, 90, 40);

        jPanel5.setLayout(null);

        jButton2.setText("Search");
        jPanel5.add(jButton2);
        jButton2.setBounds(60, 20, 130, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(40, 60, 452, 110);
        jPanel5.add(jTextField1);
        jTextField1.setBounds(220, 30, 190, 20);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(670, 320, 510, 180);

        jLabel5.setText("hall");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 170, 90, 30);

        cmbxhall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hall No 1 (500)", "Hall No 2 (250)", "Hall No 3 (150)", " " }));
        jPanel1.add(cmbxhall);
        cmbxhall.setBounds(270, 170, 160, 30);

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 400, 120, 40);

        jPanel8.setLayout(null);
        jPanel8.add(jCalendar2);
        jCalendar2.setBounds(0, 0, 470, 220);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(680, 60, 470, 230);
        jPanel1.add(txbxdate);
        txbxdate.setBounds(270, 60, 160, 30);
        jPanel1.add(txbxavalability);
        txbxavalability.setBounds(170, 260, 220, 40);

        jTabbedPane1.addTab("insert  ivent      ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel7.setText("Event ID");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 30, 80, 30);

        lblid.setText("----");
        jPanel2.add(lblid);
        lblid.setBounds(220, 30, 150, 30);

        jLabel9.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel9.setText("Name");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 150, 60, 20);

        jLabel10.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel10.setText("Address");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(60, 210, 80, 20);

        jLabel11.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel11.setText("Telephone No");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 260, 140, 30);

        jLabel12.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel12.setText("No of gusts");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(70, 360, 110, 30);
        jPanel2.add(txbxaddress);
        txbxaddress.setBounds(220, 210, 340, 30);
        jPanel2.add(txbxname);
        txbxname.setBounds(220, 150, 340, 30);

        txbxtp1.setText("mobile");
        txbxtp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txbxtp1KeyTyped(evt);
            }
        });
        jPanel2.add(txbxtp1);
        txbxtp1.setBounds(220, 260, 340, 30);

        txbxtp2.setText("land");
        txbxtp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbxtp2ActionPerformed(evt);
            }
        });
        txbxtp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txbxtp2KeyTyped(evt);
            }
        });
        jPanel2.add(txbxtp2);
        txbxtp2.setBounds(220, 310, 340, 30);

        butnSave.setText("save");
        butnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(butnSave);
        butnSave.setBounds(580, 430, 100, 50);

        butnDelete.setText("delete");
        butnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butnDeleteMouseClicked(evt);
            }
        });
        butnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(butnDelete);
        butnDelete.setBounds(720, 430, 100, 50);

        butnCancel.setText("cancel");
        jPanel2.add(butnCancel);
        butnCancel.setBounds(870, 430, 100, 50);

        jLabel15.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel15.setText("Event type");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(70, 430, 100, 20);

        cmbxeType.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        cmbxeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weddings", "Birthday parties", "Get together", "conference", "parties", " " }));
        cmbxeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxeTypeActionPerformed(evt);
            }
        });
        jPanel2.add(cmbxeType);
        cmbxeType.setBounds(220, 420, 140, 30);

        txbxgustno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txbxgustnoKeyTyped(evt);
            }
        });
        jPanel2.add(txbxgustno);
        txbxgustno.setBounds(220, 360, 340, 30);

        jLabel8.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel8.setText("Customer ID");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 90, 120, 30);

        lblCustID.setText("----");
        jPanel2.add(lblCustID);
        lblCustID.setBounds(220, 90, 100, 20);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setLayout(null);

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer name", "Telephone No", "No of gusts", "Event type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblCustomer);

        jPanel7.add(jScrollPane4);
        jScrollPane4.setBounds(30, 100, 670, 200);

        txbxsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbxsearchKeyReleased(evt);
            }
        });
        jPanel7.add(txbxsearch);
        txbxsearch.setBounds(290, 40, 240, 30);

        jLabel1.setText("search");
        jPanel7.add(jLabel1);
        jLabel1.setBounds(150, 40, 100, 40);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(630, 60, 720, 320);

        jTabbedPane1.addTab("customer details", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 170, 1380, 620);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(null);

        time.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(time);
        time.setBounds(100, 80, 170, 30);

        date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(date);
        date.setBounds(100, 40, 150, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("BACK");
        jPanel3.add(jButton3);
        jButton3.setBounds(1250, 130, 100, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aaaaaaaaaaaaaaasvfvdseventm.jpg"))); // NOI18N
        jLabel6.setText("   ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 0, 1480, 220);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1360, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnSaveActionPerformed
        //Save button of customer details
        
        String eventId =lblid.getText();
        String custID = lblCustID.getText();
        String name = txbxname.getText();
        String address =txbxaddress.getText();
        String tp1 =txbxtp1.getText();
        String tp2 =txbxtp2.getText();
        String gustsNo=txbxgustno.getText();
        String EType = cmbxeType.getSelectedItem().toString();

        try{
            String quary ="INSERT INTO customer(CustID,customerName,address,tel1,tel2)VALUES('"+custID+"','"+name+"','"+address+"','"+tp1+"','"+tp2+"')";
               pst = conn.prepareStatement(quary);
               pst.execute();
            
            String quary1  ="INSERT INTO event(eventId,no_of_gusts,EventType)VALUES('"+eventId+"','"+gustsNo+"','"+EType+"')";
               pst = conn.prepareStatement(quary1);
               pst.execute();
               
               tableload1();
               
        }
        catch(Exception e){

        }

    }//GEN-LAST:event_butnSaveActionPerformed

    private void txbxtp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbxtp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbxtp2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // save button of insert ivent
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txbxtp1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbxtp1KeyTyped
        // validate telephone
        
         try{
            char c=evt.getKeyChar();
            if(Character.isLetter(c)&&!evt.isAltDown()){
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        }catch(Exception e){

        }
        
    }//GEN-LAST:event_txbxtp1KeyTyped

    private void txbxtp2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbxtp2KeyTyped
        // validate telephone 
        
         try{
            char c=evt.getKeyChar();
            if(Character.isLetter(c)&&!evt.isAltDown()){
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        }catch(Exception e){

        }
        
    }//GEN-LAST:event_txbxtp2KeyTyped

    private void txbxgustnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbxgustnoKeyTyped
        // validate no of gusts
         try{
            char c=evt.getKeyChar();
            if(Character.isLetter(c)&&!evt.isAltDown()){
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        }catch(Exception e){

        }
        
    }//GEN-LAST:event_txbxgustnoKeyTyped

    private void cmbxeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxeTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxeTypeActionPerformed

    private void butnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnDeleteActionPerformed
        // Delete button
        
          int y = JOptionPane.showConfirmDialog(null,"Do You Want To Delete The Entry?");

        if(y==0){
            String sql = "DELETE from customer where CustID  ='"+ custID +"'";

            try {
                pst = conn.prepareStatement(sql);
                pst.execute();
                tableload1();
               butnDelete.setEnabled(false);
            }

            catch(Exception e){

            }
        }

    }//GEN-LAST:event_butnDeleteActionPerformed

    private void butnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butnDeleteMouseClicked
        // delete action 
        
         butnDelete.setEnabled(true);
        
          int row = tblCustomer.getSelectedRow();
          custID= tblCustomer.getValueAt(row, 0).toString();
    }//GEN-LAST:event_butnDeleteMouseClicked

    private void txbxsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbxsearchKeyReleased
        // search customer
        
        String search = txbxsearch.getText();
        String sql =" SELECT CustID,customerName,tel1 FROM customer where customerName LIKE '%"+ search +"%' ORDER BY `customer`.`CustID` ASC ";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.execute();
        
        }
        catch(Exception e){
        
        }
        
        
    }//GEN-LAST:event_txbxsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butnCancel;
    private javax.swing.JButton butnDelete;
    private javax.swing.JButton butnSave;
    private javax.swing.JComboBox<String> cmbxeType;
    private javax.swing.JComboBox<String> cmbxhall;
    private javax.swing.JComboBox<String> cmbxtime;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCustID;
    private javax.swing.JLabel lblid;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txbxaddress;
    private javax.swing.JTextField txbxavalability;
    private javax.swing.JTextField txbxdate;
    private javax.swing.JTextField txbxgustno;
    private javax.swing.JTextField txbxname;
    private javax.swing.JTextField txbxsearch;
    private javax.swing.JTextField txbxtp1;
    private javax.swing.JTextField txbxtp2;
    // End of variables declaration//GEN-END:variables

   
}
